src/App.tsx
src/ui/molecules/Company/OfferDescription.tsx
src/ui/molecules/ListItem.tsx
src/ui/organisms/OffersList.tsx

add offers items list

---

src/App.tsx
src/ui/atoms/Button/ShowScoreButton.tsx
src/ui/atoms/FiltersHeader/FiltersHeader.tsx

add show score button

---

src/App.tsx
src/ui/Pages/FilterPage.tsx
src/ui/atoms/Button/ClosingButton.tsx
src/ui/atoms/Button/FilterButton.tsx
src/ui/atoms/Button/ShowScoreButton.tsx
src/ui/atoms/FiltersHeader/FiltersHeader.tsx
src/ui/molecules/FilterTitle.tsx
src/ui/organisms/FilterSection.tsx

add FilterPage modal

---

src/App.tsx
src/ui/atoms/DetailOfferDescription/DetailOfferDescription.tsx
src/ui/atoms/DetailOfferDescription/SubheaderOfDescription.tsx

add detail offer description

---

src/App.tsx
src/ui/molecules/DetailOfferDescription/DetailOfferDescription.tsx
src/ui/molecules/PersonalDataInformation/PersonalDataInfromation.tsx
src/ui/molecules/ReadMore.tsx

add Personal Data Information and read more functionality

---

src/App.tsx
src/ui/atoms/Button/ApplyButton.tsx
src/ui/molecules/BottomApplyFofAnOffer/BottomApplyFofAnOffer.tsx

add bottom button applying for a job

---

package-lock.json
package.json
src/App.tsx
src/ui/Pages/OfferDetailPage.tsx
src/ui/atoms/Button/BackIconButton.tsx
src/ui/molecules/DetailOfferDescription/CoreRequirements.tsx
src/ui/molecules/DetailOfferDescription/DetailOfferDescription.tsx
src/ui/molecules/DetailOfferHeaderDescription/DetailOfferHeaderDescription.tsx

add offer detail page

---

src/App.tsx
src/ui/atoms/HeaderFormPage/HeaderFormPage.tsx

add header form page component

---

src/App.tsx
src/index.css
src/ui/Pages/MainPage.tsx
src/ui/atoms/Button/FavouriteButton.tsx
src/ui/atoms/OffersTitle/OffersTitle.tsx
src/ui/atoms/Search/Search.tsx
src/ui/molecules/PersonalDataInformation/PersonalDataInfromation.tsx
src/ui/organisms/OffersList.tsx

add MainPage View and FavouriteButton

---

src/App.tsx
src/ui/atoms/Button/AddCVButton.tsx
src/ui/atoms/HeaderFormPage/HeaderFormPage.tsx
src/ui/molecules/AddCV/AddCV.tsx

add CV Button

---

src/App.tsx
src/ui/Pages/FilterPage.tsx
src/ui/Pages/FormPage.tsx
src/ui/Pages/OfferDetailPage.tsx
src/ui/atoms/Button/ApplyButton.tsx
src/ui/atoms/Button/BackIconButton.tsx
src/ui/molecules/BottomApplyFofAnOffer/BottomApplyFofAnOffer.tsx

add FormPage

---

src/App.tsx
src/index.css
src/themes/ColorModeContext.tsx
src/ui/Pages/MainPage.tsx
src/ui/atoms/Button/BaseButton.tsx
src/ui/molecules/Company/OfferDescription.tsx
src/ui/organisms/Footer.tsx
src/ui/organisms/OffersList.tsx

add footer component, fix styles for dark theme

---

.gitignore
package-lock.json
package.json
src/App.tsx
src/base.tsx
src/hooks/useAuth.tsx
src/ui/Pages/NotFound.tsx
src/ui/organisms/Header.tsx

add firebase authentication to app

---

package-lock.json
package.json
src/App.tsx
src/app/store.ts
src/features/favorite/favorite.ts
src/main.tsx

add simple reducer with redux toolkit to app

---

src/api/api.ts
src/api/models.ts

add models

---

src/api/serverURL.ts
src/hooks/useFetchOfferData.tsx
src/ui/Pages/OfferDetailPage.tsx
src/ui/molecules/DetailHeaderTitle/DetailHeaderTitle.tsx
src/ui/organisms/DetailHeader.tsx

add offerData fetch

---

src/ui/Pages/MainPage.tsx
src/ui/atoms/Search/Search.tsx
src/ui/organisms/OffersList.tsx

add connected search input to backend

---

.babelrc
package-lock.json
package.json
src/App.tsx
src/themes/ColorModeContext.tsx
src/ui/Pages/MainPage.tsx
src/ui/Pages/OfferDetailPage.tsx
src/ui/atoms/Search/Search.tsx
src/ui/molecules/ListItem.tsx
src/ui/organisms/Header.tsx

77# loading spinner

---

src/hooks/useFetchOffersData.tsx
src/ui/Pages/MainPage.tsx
src/ui/atoms/NoOffersFound/NoOffersFound.tsx

add No offers found information

---

src/ui/Pages/FormPage.tsx
src/ui/atoms/Button/BaseButton.tsx
src/ui/molecules/ApplicationSend/ApplicationSend.tsx

add information: Application Send in FormPage

---

src/ui/Pages/MainPage.tsx
src/ui/atoms/Button/ClosingButton.tsx
src/ui/atoms/Button/FavouriteButton.tsx
src/ui/atoms/Button/FilterButton.tsx

Change buttons "filtry" and "ulubione oferty" on Main Mage on desktop
